Repository symbiote/silverstripe-advancedworkflow, pull requests merged in 2019-04, with the labels that each got.

#392 Add test for NotifyUsersWorkflowAction and fix #391
  code/actions/NotifyUsersWorkflowAction.php
  tests/WorkflowEngineTest.php
Labels: affects/v3, change/patch

#388 Only mark fields as readonly (not form)
  src/Extensions/AdvancedWorkflowExtension.php
Labels: affects/v4, change/minor

#393 FIX {$Context.LinkToPendingItems} now provides the correct URL to edit the current workflow
  src/Extensions/WorkflowApplicable.php
Labels: affects/v4, change/patch

#394 FIX Workflow Actions tab now renders HTML content inside a div instead of a paragraph tag
  src/DataObjects/WorkflowActionInstance.php
  templates/Symbiote/AdvancedWorkflow/DataObjects/WorkflowActionInstance/ReadonlyField.ss
Labels: affects/v4, change/patch
